<a href="https://colab.research.google.com/github/smel0722/class/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

###使用np.array()建立陣列
https://github.com/MyDearGreatTeacher

In [6]:
import numpy as np
print("numpy version: %s" % np.__version__)
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)


numpy version: 1.16.3
[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


In [11]:
import numpy as np
print("numpy version: %s" % np.__version__)
a =np.zeros((2, 3))
b =np.arange(2, 3, 0.1) # start, end, step end not in line
c =np.linspace(1, 4, 6) # start, end, num
d =np.indices((3, 3))

print(a)
print(b)
print(c)
print(d)

numpy version: 1.16.3
[[0. 0. 0.]
 [0. 0. 0.]]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[1.  1.6 2.2 2.8 3.4 4. ]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


***作業***


---



In [12]:
import numpy as np
print("numpy version: %s" % np.__version__)

a= np.linspace(2.0, 3.0, num=5)

b=np.linspace(2.0, 3.0, num=5, endpoint=False)

c=np.linspace(2.0, 3.0, num=5, retstep=True)

print(a)
print(b)
print(c)

numpy version: 1.16.3
[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


***N維陣列的屬性***

---



In [25]:
import numpy as np
print("numpy version: %s" % np.__version__)
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array
ar2.shape
ar2.ndim


numpy version: 1.16.3


2

***Array shape manipulation***


In [24]:

x = np.arange(4)
print(x)
x2 = x.reshape(4,1)
print(x2)
x2.shape


[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


(4, 1)

***1D ARRAY***



In [46]:
a=np.array([[0,1],[2,3]])
print(a)
x =a.reshape(1,4)
print(x)

y = a.reshape(4,1)
print(y)
x.shape


[[0 1]
 [2 3]]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


(1, 4)

***2D array*** 

In [47]:
a=np.array([[0,1],[2,3]])
print(a)
x =a.reshape(1,4)
print(x)

y = a.reshape(4,1)
print(y)

y.shape

[[0 1]
 [2 3]]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


(4, 1)

***2D array*** 

In [43]:
x = np.arange(2,10).reshape(2,4)
print(x)
y =np.arange(2,10).reshape(4,2)
print(y)
#z =np.arange(2,10).reshape(4,4)
#print(z)

[[2 3 4 5]
 [6 7 8 9]]
[[2 3]
 [4 5]
 [6 7]
 [8 9]]


***3D array***

In [51]:
x = np.arange(0,64).reshape(2,4,8)
print(x)

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]]

 [[32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]
  [48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]]]


***3D array***



In [52]:
x = np.arange(0,64).reshape(8,4,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]

 [[32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]]

 [[48 49]
  [50 51]
  [52 53]
  [54 55]]

 [[56 57]
  [58 59]
  [60 61]
  [62 63]]]


***Array shape manipulationFlattening a multi-dimensional array***

In [60]:
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar
ar.ravel()
print(ar)
z = ar.T.ravel()
print(z)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
[ 1 10  2 11  3 12  4 13  5 14]


***Numpy的 2D random***

In [62]:
np.random.rand(4,3)


array([[0.69297233, 0.97717359, 0.54802378],
       [0.10987069, 0.85136544, 0.64981101],
       [0.8304694 , 0.67455508, 0.13432979],
       [0.24313528, 0.05389671, 0.57269504]])

***Numpy的 3D random***

In [63]:
np.random.rand(4,3,2)


array([[[0.94686711, 0.83496354],
        [0.09364436, 0.79070943],
        [0.56678652, 0.74506706]],

       [[0.28708356, 0.95826757],
        [0.72043013, 0.79853159],
        [0.62122096, 0.02244235]],

       [[0.85774318, 0.633189  ],
        [0.96887724, 0.44058709],
        [0.01035035, 0.69761919]],

       [[0.42107472, 0.33996762],
        [0.30754821, 0.46647568],
        [0.2630231 , 0.01297857]]])

***numpy.random.randint()***


In [71]:
c =np.random.randint(1,size=5)   
print(c)
a=np.random.randint(1,5)           
print(a)
b=np.random.randint(-5,5,size=(2,2))
print(b)

[0 0 0 0 0]
4
[[-3 -5]
 [-4  3]]


***numpy.random.seed()***

In [73]:
np.random.seed(0)
a = np.random.rand(5)
print(a)
np.random.seed(1676)
b=np.random.rand(5)
print(b)
np.random.seed(1676)
c=np.random.rand(5)
print(c)


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.39983389 0.29426895 0.89541728 0.71807369 0.3531823 ]
[0.39983389 0.29426895 0.89541728 0.71807369 0.3531823 ]
